### ISSUE TITLE
[BUG] Requirements not installing correctly?

### ISSUE THREAD

**Issue by DevilXD** [solsticegamestudios/steam#10]
**Description**

The requirements appear not to install correctly. Specifically, the `wsproto` package was not installed for some reason, after running the install command several times in different configurations. If case that matters, I was trying to install it on an Ubuntu 22 LTS machine, into a "Redv3" venv folder. The first command was meant to replace the now-outdated official 1.4.4 version of the library, assuming the requirements didn't change. This was followed by an update command meant to take care of any missing dependencies, and finally a full reinstall of the library and it's requirements - none worked as expected.

**Steps to Reproduce the behavior**

Here's the Ubuntu log:

[linux.txt](https://github.com/user-attachments/files/18854278/linux.txt)

I also tried it on Windows, and it also failed to install the dependencies, although it was a different one this time:

[windows.txt](https://github.com/user-attachments/files/18854280/windows.txt)

**Expected behavior**

Installation installs all required dependencies, and import happens as expected.

**Screenshots**

*Not applicable*

**Versions Report**

This is from Ubuntu, taken right after the log:

```yaml
steam: 1.6.1

Dependencies:
                 vdf: 4.0
            protobuf: 3.20.3
            requests: 2.32.3
          cachetools: 5.5.1
              gevent: 24.11.1
 gevent-eventemitter: 2.1
       pycryptodomex: 3.21.0
              enum34: Not Installed
       win-inet-pton: Not Installed

Python runtime:
          executable: /home/ubuntu/Redv3/bin/python
             version: 3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0]
            platform: linux

System info:
              system: Linux
             machine: x86_64
             release: 6.8.0-1019-oracle
             version: #20~22.04.1-Ubuntu SMP Wed Jan 22 13:00:47 UTC 2025
```
